require File.dirname(__FILE__) + '/config'
require File.dirname(__FILE__) + '/drupal_base'
require File.dirname(__FILE__) + '/node'
require File.dirname(__FILE__) + '/variable'
require File.dirname(__FILE__) + '/vocabulary'
require File.dirname(__FILE__) + '/term_data'
require File.dirname(__FILE__) + '/url_alias'
require File.dirname(__FILE__) + '/locales_meta'
require File.dirname(__FILE__) + '/user'
require File.dirname(__FILE__) + '/term_node'
require File.dirname(__FILE__) + '/node_revision'
require File.dirname(__FILE__) + '/filter'
require File.dirname(__FILE__) + '/comment'
require File.dirname(__FILE__) + '/upload'
require File.dirname(__FILE__) + '/file'

